name: Lint & test

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

env:
  NODE_VERSION: 16
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v2
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn run lint:eslint
      - name: Run stylelint
        run: yarn run lint:stylelint
      - run: echo "✅ GOOD JOB 👌"
      